# nginx-values.yaml
controller:
  service:
    annotations:
      # Use Network Load Balancer (NLB)
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      # Enable cross-zone load balancing
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      # Use internal load balancer if needed
      # service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      
  # Configure resources
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # Configure autoscaling
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  # Configure metrics for monitoring
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  # Configure logging
  config:
    log-format-upstream: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id'
